batch_size: 16
height: 32
lr: 0.0003
max_txt_len: 40
model_path: D:/Projects/reciept-scanner/RCNN/models/202408310048
name: CRNNGREY
train_epochs: 100
vocab: "s&*/^<6rBAE+iN}mXn!3.#ST@l] Y:KPd-=HM_0$h)G\"7Lc'U%~?R;Da[\\F{IQe2C95\xB7\
  O|`J,V4W1>(8Z"
width: 128
