# Use an official Python runtime as a parent image
FROM python:3.10.11-slim

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender-dev \    
    libgl1-mesa-glx \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /api

# Copy the current directory contents into the container at /api
COPY /api .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Define environment variable to point to the Flask app
ENV FLASK_APP=flask_server.py

# Enable Flask to run in production mode (optional)
ENV FLASK_ENV=production

# Run the Flask development server
CMD ["gunicorn", "-w", "1", "-b", "0.0.0.0:5000", "flask_server:app"]
