apiVersion: v1
kind: Service
metadata:
  name: flask-server-service
spec:
  selector:
    app: flask-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30001 
  type: NodePort


# audjust this later