batch_size: 16
height: 32
lr: 0.001
max_txt_len: 40
mean: 199.97754
model_path: D:/Projects/reciept-scanner/RCNN/models/202409040045
name: CRNNGREY
std: 104.89471
train_epochs: 100
vocab: "/>]A=+Bd2_7$&3\"*XJrR0^P\xB7 [1`'9W\\e?:Q4EZULMNY8is)hC!K|I%V.naTS},-;65(FG{D@~lc#<HmO"
width: 128
